### ISSUE TITLE
Optimize http requests - Refactor map.cs

### ISSUE THREAD

**Issue by wilhelmberg** [mapbox/mapbox-sdk-cs#29]
refs #11 

From my point of view some logic should move from `Core/Tile.cs` to `Core/Map.cs` that should keep track of:

* [x] tiles needed for current map extent
* [x] threaded tile fetching #23
* [x] retrying failed tiles #24
* [ ] throttling tile requests #25
* [ ] aborting tile requests #26
* [x] caching tiles #27
* [x] reporting progress of tile loading #28
